version: '1'
services:
  mysql:    
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'qwerty123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      -  mysqlvol:/var/lib/mysql
# Names our volume
volumes:
  mysqlvol: